(ns datomic-blockchain.traceability.test-completeness
  "Direct tests for the completeness-assessment interface.

  These pin the contract the QR interface, the authenticated trace, and
  the labeled-path evaluation harness rely on: the six signals, the
  published weights, the nil-renormalization semantics, and the named
  missing evidence per defect."
  (:require [clojure.test :refer [deftest is testing use-fixtures]]
            [datomic.api :as d]
            [datomic-blockchain.test-support :as ts]
            [datomic-blockchain.traceability.completeness :as completeness])
  (:import [java.util UUID]))

;; =============================================================================
;; Fixture: a minimal provenance hop with defect knobs
;; =============================================================================

(defn- seed-hop!
  "Seed one provenance hop and return the entity's PROV uuid.

  Knobs:
    :with-activity?    entity is generated by an activity (default true)
    :with-agent?       the activity names a responsible agent (default true)
    :with-start-time?  the activity carries :prov/startedAtTime (default true)
    :valid-time-order? the activity's end is after its start (default true)
    :with-parent?      the entity derives from a parent hop
                       (default false)
    :with-parent-agent? the parent hop's activity names its agent
                       (default true; only meaningful with :with-parent?)"
  [conn & {:keys [with-activity? with-agent? with-start-time? valid-time-order?
                  with-parent? with-parent-agent?]
           :or {with-activity? true with-agent? true with-start-time? true
                valid-time-order? true with-parent? false with-parent-agent? true}}]
  (let [entity-uuid (UUID/randomUUID)
        activity-uuid (UUID/randomUUID)
        agent-uuid (UUID/randomUUID)
        parent-uuid (UUID/randomUUID)
        parent-activity-uuid (UUID/randomUUID)
        started #inst "2024-05-01T08:00:00.000-00:00"
        ended #inst "2024-05-01T09:00:00.000-00:00"
        ended-before #inst "2024-05-01T07:00:00.000-00:00"
        parent-activity-tx (cond-> {:db/id "parent-activity"
                                    :prov/activity parent-activity-uuid
                                    :prov/activity-type :activity/milking
                                    :prov/startedAtTime started
                                    :prov/endedAtTime ended}
                             with-parent-agent?
                             (assoc :prov/wasAssociatedWith agent-uuid))
        parent-txs (cond-> [{:db/id "parent"
                             :prov/entity parent-uuid
                             :prov/entity-type :product/raw-milk
                             :prov/wasGeneratedBy parent-activity-uuid}]
                     ;; derive the parent from nothing upstream: empty hop list
                     true
                     (into [parent-activity-tx
                           {:db/id "agent"
                            :prov/agent agent-uuid
                            :prov/agent-name "Test Farm"
                            :prov/agent-type :organization/farmer}]))
        activity-tx (cond-> {:db/id "activity"
                             :prov/activity activity-uuid
                             :prov/activity-type :activity/uht-processing}
                      with-start-time?
                      (assoc :prov/startedAtTime started)

                      (and with-start-time? valid-time-order?)
                      (assoc :prov/endedAtTime ended)

                      (and with-start-time? (not valid-time-order?))
                      (assoc :prov/endedAtTime ended-before)

                      with-agent?
                      (assoc :prov/wasAssociatedWith agent-uuid))
        entity-tx (cond-> {:db/id "entity"
                           :prov/entity entity-uuid
                           :prov/entity-type :product/plain-uht
                           :traceability/batch "TEST-BATCH-001"}
                    with-activity? (assoc :prov/wasGeneratedBy activity-uuid)
                    with-parent? (assoc :prov/wasDerivedFrom parent-uuid))]
    @(d/transact conn (concat parent-txs (when with-activity? [activity-tx]) [entity-tx]))
    entity-uuid))

(defn- assess
  [conn entity-uuid & [opts]]
  (completeness/assess-completeness (d/db conn) entity-uuid (or opts {})))

(defn- approx=
  [expected actual]
  (< (Math/abs (- expected actual)) 1e-9))

;; =============================================================================
;; The six signals on a complete hop
;; =============================================================================

(use-fixtures :each (fn [f] (f) (ts/retire-all!)))

(deftest complete-hop-scores-one-test
  (testing "a fully-evidenced hop scores 1.0 with no missing evidence"
    (let [conn (ts/fresh-conn)
          entity-uuid (seed-hop! conn)
          result (assess conn entity-uuid)]
      (is (= :assessed (:status result)))
      (is (approx= 1.0 (:completeness-score result)))
      (is (= [] (:missing-evidence result)))
      (is (= 1 (:path-count result))))))

;; =============================================================================
;; One defect at a time — the named missing evidence matches the defect
;; =============================================================================

(deftest missing-activity-defect-test
  (testing "no generating activity: activity-present is named and the
            nil-renormalization contract holds (unknown signals are
            excluded from the denominator, so the hop scores 0.5 not 0)"
    (let [conn (ts/fresh-conn)
          entity-uuid (seed-hop! conn :with-activity? false)
          result (assess conn entity-uuid)]
      (is (= :assessed (:status result)))
      (is (approx= 0.5 (:completeness-score result)))
      (is (= ["activity-present"] (:missing-evidence result))))))

(deftest missing-agent-defect-test
  (testing "no responsible agent: agent-present is named, score reflects
            the published agent weight of 0.20 over a full denominator"
    (let [conn (ts/fresh-conn)
          entity-uuid (seed-hop! conn :with-agent? false)
          result (assess conn entity-uuid)]
      (is (approx= 0.80 (:completeness-score result)))
      (is (= ["agent-present"] (:missing-evidence result))))))

(deftest missing-start-time-defect-test
  (testing "no start time: time-start-present is named and time-order
            becomes unknown (excluded), not missing"
    (let [conn (ts/fresh-conn)
          entity-uuid (seed-hop! conn :with-start-time? false)
          result (assess conn entity-uuid)]
      (is (approx= (/ 0.70 0.90) (:completeness-score result)))
      (is (= ["time-start-present"] (:missing-evidence result))))))

(deftest invalid-time-order-defect-test
  (testing "end before start: time-order-valid is named as missing"
    (let [conn (ts/fresh-conn)
          entity-uuid (seed-hop! conn :valid-time-order? false)
          result (assess conn entity-uuid)]
      (is (approx= 0.90 (:completeness-score result)))
      (is (= ["time-order-valid"] (:missing-evidence result))))))

;; =============================================================================
;; Ranking: complete above defective — the face-validity check
;; =============================================================================

(deftest complete-hop-outranks-defective-hops-test
  (testing "the complete hop scores above every single-defect hop"
    (let [conn (ts/fresh-conn)
          complete (assess conn (seed-hop! conn))
          defective [(assess conn (seed-hop! conn :with-activity? false))
                     (assess conn (seed-hop! conn :with-agent? false))
                     (assess conn (seed-hop! conn :with-start-time? false))
                     (assess conn (seed-hop! conn :valid-time-order? false))]]
      (doseq [result defective]
        (is (> (:completeness-score complete) (:completeness-score result)))))))

;; =============================================================================
;; Absent entity is not score 0.0 — it is its own status
;; =============================================================================

(deftest absent-entity-test
  (testing "an entity that does not exist is :entity-absent, distinct from
            an assessed path that happens to be incomplete"
    (let [conn (ts/fresh-conn)
          result (assess conn (UUID/randomUUID))]
      (is (= :entity-absent (:status result)))
      (is (approx= 0.0 (:completeness-score result)))
      (is (= [] (:missing-evidence result)))
      (is (= 0 (:path-count result))))))

;; =============================================================================
;; Multi-hop paths average hop scores, and missing evidence names the hop
;; =============================================================================

(deftest multi-hop-path-averages-hop-scores-test
  (testing "a complete child derived from a complete parent scores 1.0 over two hops"
    (let [conn (ts/fresh-conn)
          child (assess conn (seed-hop! conn :with-parent? true))]
      (is (= 1 (:path-count child)))
      (is (approx= 1.0 (:completeness-score child)))))
  (testing "a defective parent drags the path average and its defect is named"
    (let [conn (ts/fresh-conn)
          child-uuid (seed-hop! conn :with-parent? true :with-parent-agent? false)
          result (assess conn child-uuid)]
      ;; path average of a complete child hop (1.0) and an agent-less
      ;; parent hop (0.8)
      (is (approx= 0.90 (:completeness-score result)))
      (is (= ["agent-present"] (:missing-evidence result))))))

;; =============================================================================
;; The weights knob: ablation by zeroing one signal
;; =============================================================================

(deftest weights-override-is-the-ablation-knob-test
  (testing "zeroing the agent weight lifts the missing-agent hop to 1.0 —
            the documented ablation semantics for the paper"
    (let [conn (ts/fresh-conn)
          entity-uuid (seed-hop! conn :with-agent? false)
          default (assess conn entity-uuid)
          ablated (assess conn entity-uuid {:weights {:agent-present 0.0}})]
      (is (approx= 0.80 (:completeness-score default)))
      (is (approx= 1.0 (:completeness-score ablated))))))
